import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';
import StoreProvider from '@/app/StoreProvider';
import LoadingTopBar from '@/components/common/LoadingTopBar';
import Navbar from '@/components/common/Navbar';
const dm_sans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * RootLayout component that provides the main layout structure for the application.
 *
 * This component wraps the entire application, setting up global styles,
 * language settings, and providing a context for state management. It also includes
 * a loading bar at the top of the page and a toaster for notifications.
 *
 * @component
 *
 * @param {React.ReactNode} props.children - The page to be rendered within the layout.
 *
 * @returns {JSX.Element} The rendered RootLayout component.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className + 'box-border h-screen w-screen'}>
        <div className="h-full w-full overflow-auto bg-background pt-20">
          <Toaster
            position="top-center"
            gutter={8}
            toastOptions={{ className: 'w-96' }}
          />
          <Navbar />
          <StoreProvider>
            <>
              <LoadingTopBar />
              {children}
            </>
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
